##===- deadlocker/tools/deadlocker ------------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=deadlocker

include $(LEVEL)/Makefile.common
